language: cpp

addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - cmake
    - gfortran
    - build-essential
    - pkg-config
    - realpath
    - libwxgtk3.0-dev

install:
  - mkdir build;

script:
  - cd build; cmake -Dtest=ON ../; make;

