/* Autogenerated by png2wx.pl on Fri Apr  7 05:07:05 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_ensemble_weather;

#endif /* ICONS_H */
